---
title: Numerical Stability
author: ''
date: '2017-06-27'
slug: numerical-stability
categories:
  - announcements
tags:
  - r
  - numeric-stability
---

# Overview

When writing algorithms to compute different routines, it is imperative that the value the routine produces is correct. To obtain numerically valid results, we need to ensure that the underlying routines are able to work with how the computer is able to represent a data type. 

Review common errors: <http://spm.thecoatlessprofessor.com/r-programming-done-wrong.html>

# Files of Interest 

Rendered Files:

* [Lecture 9: Numerical Stability  (PDF)](/assets/lectures/lec09/lec09_numerical_stability_errors_and_debugging_techniques.pdf)

Generation Files:

* [Lecture 9: Numerical Stability (Rmd)](/assets/lectures/lec09/lec09_numerical_stability_errors_and_debugging_techniques.Rmd)
* [Lecture 9: Numerical Stability (R)](/assets/lectures/lec09/lec09_numerical_stability_errors_and_debugging_techniques.R)


# Source Material

Source of all materials: 

* <https://github.com/stat385uiuc/su2017/tree/master/static/assets/lectures/lec09>
